cookie:
  expiry_days: 30
  key: abcxyz
  name: ehspeakinghomework
credentials:
  usernames:
    quangnguyen:
      email: null
      name: Nguyen Dang Quang
      password: $2b$12$4CmQnkL7Db7RUIz3dFtzlORjWZDrmsPSRc.C4f2ZVwuGI3dMlHDhe
    msmai:
      email: mai.nguyen.118@gmail.com
      name: Nguyen Thi Xuan Mai
      password: $2b$12$j/Dz8aDJJU0z6Du2fSpd1uzFpK18sFAzX4CyP6rELYbMSR3XogPaS
    anhpham:
      email: null
      name: Pham Dao Mai Anh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    anhnguyen:
      email: null
      name: Nguyen Ho Phuong Anh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    baonguyen:
      email: null
      name: Nguyen Kim Bao
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    handao:
      email: null
      name: Dao Hong Han
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    linhdang:
      email: null
      name: Dang Phuong Linh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    linhnguyen:
      email: null
      name: Nguyen Hoang Phuong Linh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    longdang:
      email: null
      name: Dang Hoang Long
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    mynguyen:
      email: null
      name: Nguyen Ha My
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    nhitran:
      email: null
      name: Tran Thi Yen Nhi
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    nhungnguyen:
      email: null
      name: Nguyen Hong Nhung
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    nhunguyen:
      email: null
      name: Nguyen Thao Nhu
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    quynhphan:
      email: null
      name: Phan Nhu Quynh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    thole:
      email: null
      name: Le Ngoc Tho
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    tramtruong:
      email: null
      name: Truong Thi Bich Tram
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    trietle:
      email: null
      name: Le Minh Triet
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    vyhuynh:
      email: null
      name: Huynh Thanh Vy
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    xuannguyen:
      email: null
      name: Nguyen Hoang Nhu Xuan
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    anle:
      email: null
      name: Le Trieu An
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    dungnguyen:
      email: null
      name: Nguyen Ngoc Phuong Dung
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    duongnguyen:
      email: null
      name: Nguyen Hoang Thai Duong
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    dattran:
      email: null
      name: Tran Quoc Dat
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    giangluong:
      email: null
      name: Luong Vu Huong Giang
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    hatruong:
      email: null
      name: Truong Le Viet Ha
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    huytrinh:
      email: null
      name: Trinh Gia Huy
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    khangtruong:
      email: null
      name: Truong Long Khang
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    khanhta:
      email: null
      name: Ta Le Duy Khanh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    linhdo:
      email: null
      name: Do Khanh Linh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    mainguyen:
      email: null
      name: Nguyen Thanh Mai
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    minhtran:
      email: null
      name: Tran Thi Nhat Minh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    ngandinh:
      email: null
      name: Dinh Nguyen Thao Ngan
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    ngocpham:
      email: null
      name: Pham Bao Ngoc
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    ngocdo:
      email: null
      name: Do Nhu Ngoc
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    nhannguyen:
      email: null
      name: Nguyen Ngoc Hien Nhan
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    phathoang:
      email: null
      name: Hoang Gia Thinh Phat
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    thaohoang:
      email: null
      name: Hoang Thanh Thao
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    thunguyen:
      email: null
      name: Nguyen Ngoc Minh Thu
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    tinhtruong:
      email: null
      name: Truong Duc Tinh
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    trangngo:
      email: null
      name: Ngo Thuy Trang
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    trangtran:
      email: null
      name: Tran Nguyen Ngoc Trang
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    trannguyen:
      email: null
      name: Nguyen Hoang Le Bao Tran
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    trucnguyen:
      email: null
      name: Nguyen Kim Truc
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    vyong:
      email: null
      name: Ong Minh Vy
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    ynguyen:
      email: null
      name: Nguyen Hong Nhu Y
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
    yennguyen:
      email: null
      name: Nguyen Hai Yen
      password: $2b$12$1sOxcL70rWFT1dnozPu6aOJeZ5lPaAzHULmVjC5ZsWYFMTV4GQQY2
preauthorized:
  emails:
  - quangnd159@gmail.com
